// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cs: [{type: 'autogenerated', dirName: 'main'}],
  cooking: [{type: 'autogenerated', dirName: 'cooking'}],
};

module.exports = sidebars;
